parameters:
#    freebeats_survey.example.class: freebeats\SurveyBundle\Example

services:
#    freebeats_survey.example:
#        class: %freebeats_survey.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
