freebeats_customer_homepage:
    pattern:  /customer
    defaults: { _controller: freebeatsCustomerBundle:Default:index }

freebeats_subscribe_homepage:
    pattern:  /subscribe
    defaults: { _controller: freebeatsCustomerBundle:Default:index }

freebeats_customer_create:
    pattern:  /customer/create
    defaults: { _controller: freebeatsCustomerBundle:Default:create }

freebeats_customer_pay:
    pattern:  /customer/pay
    defaults: { _controller: freebeatsCustomerBundle:Default:pay }
    
freebeats_customer_pay_success:
    pattern:  /customer/pay/success
    defaults: { _controller: freebeatsCustomerBundle:Default:paySuccess }

freebeats_customer_pay_failed:
    pattern:  /customer/pay/failed
    defaults: { _controller: freebeatsCustomerBundle:Default:payFailed }
    
freebeats_customer_success:
    pattern:  /customer/success
    defaults: { _controller: freebeatsCustomerBundle:Default:createSuccess }
    
freebeats_customer_details:
    pattern:  /customer/show/{id}
    defaults: { _controller: freebeatsCustomerBundle:Default:show }
    
freebeats_customer_update:
    pattern:  /customer/update/{id}
    defaults: { _controller: freebeatsCustomerBundle:Default:update }