freebeats_customer_list:
    pattern:  /home
    defaults: { _controller: freebeatsCustomerBundle:Default:index }

freebeats_customer_create:
    pattern:  /create
    defaults: { _controller: freebeatsCustomerBundle:Default:create }
    
freebeats_customer_details:
    pattern:  /show/{id}
    defaults: { _controller: freebeatsCustomerBundle:Default:show }
    
freebeats_customer_update:
    pattern:  /update/{id}
    defaults: { _controller: freebeatsCustomerBundle:Default:update }