freebeats_customer_homepage:
    pattern:  /customer
    defaults: { _controller: freebeatsCustomerBundle:Default:index }

freebeats_subscribe_homepage:
    pattern:  /subscribe
    defaults: { _controller: freebeatsCustomerBundle:Default:index }

freebeats_customer_create:
    pattern:  /customer/create
    defaults: { _controller: freebeatsCustomerBundle:Default:create }
    
freebeats_customer_details:
    pattern:  /customer/show/{id}
    defaults: { _controller: freebeatsCustomerBundle:Default:show }
    
freebeats_customer_update:
    pattern:  /customer/update/{id}
    defaults: { _controller: freebeatsCustomerBundle:Default:update }