parameters:
#    freebeats_contact.example.class: freebeats\ContactBundle\Example

services:
#    freebeats_contact.example:
#        class: %freebeats_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
