freebeats_home_homepage:
    pattern:  /home
    defaults: { _controller: freebeatsHomeBundle:Default:index }
    
freebeats_home_contactus:
    pattern:  /contactus
    defaults: { _controller: freebeatsHomeBundle:Default:contactUs }
    
freebeats_home_contactus_success:
    pattern: /contact/success
    defaults: { _controller: freebeatsHomeBundle:Defaults:contactUsSuccess }
    
freebeats_about_terms_conditions:
    pattern:  /terms-and-conditions
    defaults: { _controller: freebeatsHomeBundle:Default:termsandconditions }

freebeats_home_sitemap:
    pattern:  /sitemap
    defaults: { _controller: freebeatsHomeBundle:Default:sitemap }